ocn(dependencies): Track `DeviceSettings` from LineageOS for missing styles
out/soong/.intermediates/device/htc/ocn/gestures/GestureHandler/android_common/manifest_fixer/AndroidManifest.xml:13: error: resource style/Theme.Main (aka org.lineageos.settings.device:style/Theme.Main) not found.
error: failed processing manifest.

Signed-off-by: tejHackerDev <tejasimha222@gmail.com>