ocn(gestures): Fix missing intent for camera gesture
device/htc/ocn/gestures/src/org/lineageos/settings/device/HTCSuperGestures.java:
125: error: cannot find symbol
        final Intent intent = new Intent(Intent.ACTION_SCREEN_CAMERA_GESTURE);

Signed-off-by: tejHackerDev <tejasimha222@gmail.com>